### ISSUE TITLE
property_hook doesn't trigger when grandparent properties change

### ISSUE THREAD

**Issue by cgmb** [woboq/property_bindings#1]
I noticed that dependent properties only seem to update when dependent on independent properties, or when queried. Unfortunately, that breaks hooks with grandparents.

Hooks need to be triggered regardless of whether the new value is queried or not. Typically they exist because we need to break out of the property system and indirectly trigger a query. e.g. GraphicsRectObject::color -> GraphicsRectObject::update -> GraphicsRectObject::paint.

Example:

```
#include <iostream>
#include "property.h"

struct Rectangle {
  property<double> width;
  property<double> height;
  property<double> area {
    [&](){ return width * height; }
  };
};

void printA() { std::cout << "A"; }
void printB() { std::cout << "B"; }

int main() {
  Rectangle r;

  property_hook<double> hookA(
    printA, [&]{ return r.width * r.height; });

  property_hook<double> hookB(
    printB, [&]{ return r.area; });

  r.width = 5;

  std::cout << std::endl;
}
```

Actual Output:
`A`

Expected Output:
`AB`

**Comment by ogoffart** [comment]
Thanks for looking into that.

It is really unintuitive, but what happens here is that your lambda returns a copy of the property.
 `[&]{ return r.area; }`  is in fact returning the type `property<double>`  rather than a double.  It can be converted to a `std::function<double>` but then the hookB is 'listening' to the wrong property.

To fix the problem in that code, you can do one of the following:
- `[&]()->double{ return r.area; })`
- `[&]{ return r.area.get(); })`

In order to avoid this code to compile, one could forbid the automatic conversion to T on temporaries.  That is, change the operatorT in property to:

``` c++
  operator const T&() const & { return get(); }
  operator const T&() && = delete;
```

**Comment by cgmb** [comment]
Thanks for the detailed response. I'll be sure to specify a return type going forward.
